spring:
  application:
    name: lottery-config
  profiles:
      active: native
  rabbitmq:
      host: ${RABBIT_MQ_HOST:127.0.0.1}
      port: ${RABBIT_MQ_PORT:5672}
      username: guest
      password: guest
#配置文件在本地
  cloud:
    config:
      server:
        native:
          #在Windows系统中如果路径是一个带盘符的绝对路径，那么开发人员需要额外的“/”，如下： file:///${user.home}/config-repo
          search-locations: /home/lottery/config
    bus:
      trace:
        enabled: true  #开启消息跟踪
#配置文件在git服务器配置
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/chengbinbbs/lotteryconfig/
#          search-paths: config
#          default-label: master
#          username: ${username}
#          password: ${password}

#利用消息总线spring cloud bus来刷新配置时，需要【POST】调用http://localhost:8085/bus/refresh
#需要关闭安全验证
management:
  security:
    enabled: false

security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456

server:
  port: 8095
  undertow:
     worker-threads: 20
     buffer-size: 512
     io-threads: 2
  compression:
    enabled: true
    mime-types: text/xml,text/css,text/plain,application/xml,application/json,application/javascript
    min-response-size: 1024


eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer1:8081/eureka,http://root:123456@peer2:8082/eureka,http://root:123456@peer3:8083/eureka


## LOGGING
logging:
  path: F://log
  config: classpath:config/logback.xml
  level:
    application: INFO
    com.netflix: WARN
    druid.sql: WARN
    com.github.chengbin: INFO
    org.apache.http: WARN
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.boot: WARN
    org.thymeleaf: WARN






